Repository ISISComputingGroup/IBEX_device_generator, pull requests merged in 2022-08, with the labels that each got.

#24 Added 'hasDefault' to config template.
  templates/ioc/config.xml
Labels: size/XS

#23 prompt to manually create repo if no token specified
  IBEX_device_generator.py
  utils/support_utils.py
Labels: size/S

#22 Ticket4659 fix git support
  IBEX_device_generator.py
  README.md
  utils/common_utils.py
  utils/git_utils.py
  utils/requests_utils.py
  utils/support_utils.py
Labels: size/L

#25 Update README.md
  README.md
Labels: size/XS
